### ISSUE TITLE
error combo_locks

### ISSUE THREAD

**Issue by aka0kuro** [valorekhov/ovos-arch-linux#2]
The installation was perfect. When restarting, the ovo loading screen appears. The problem is that the background of eggs and a rotating circle in the upper right part remain on the screen. When entering through ssh and trying to load ovos-core or ovos-PHAL and other ovos programs. It gives me the following combo lock error.

`Traceback (most recent call last):
  File "/usr/bin/ovos-core", line 5, in <module>
    from ovos_core.__main__ import main
  File "/usr/lib/python3.11/site-packages/ovos_core/__init__.py", line 15, in <module>
    from ovos_config.config import Configuration
  File "/usr/lib/python3.11/site-packages/ovos_config/__init__.py", line 1, in <module>
    from ovos_config.config import Configuration, LocalConf, RemoteConf
  File "/usr/lib/python3.11/site-packages/ovos_config/config.py", line 40, in <module>
    class Configuration(dict):
  File "/usr/lib/python3.11/site-packages/ovos_config/config.py", line 44, in Configuration
    default = MycroftDefaultConfig()
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ovos_config/models.py", line 168, in __init__
    super().__init__(DEFAULT_CONFIG)
  File "/usr/lib/python3.11/site-packages/ovos_config/models.py", line 141, in __init__
    super().__init__(path)
  File "/usr/lib/python3.11/site-packages/ovos_config/models.py", line 65, in __init__
    self.load_local(path)
  File "/usr/lib/python3.11/site-packages/ovos_config/models.py", line 98, in load_local
    with self.__lock:
  File "/usr/lib/python3.11/site-packages/combo_lock/combo_lock.py", line 92, in __enter__
    self.acquire()
  File "/usr/lib/python3.11/site-packages/combo_lock/combo_lock.py", line 58, in acquire
    result = self._acquire(blocking)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/combo_lock/combo_lock.py", line 82, in _acquire
    self.plock.acquire()
  File "/usr/lib/python3.11/site-packages/filelock/_api.py", line 217, in acquire
    self._acquire()
  File "/usr/lib/python3.11/site-packages/filelock/_unix.py", line 36, in _acquire
    fd = os.open(self.lock_file, open_flags, self._context.mode)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/tmp/combo_locks/b3Zvc19jb25maWc=.lock'
`

**Comment by valorekhov** [comment]
I'm in the similar state with my build.. The "loading indicator" keeps going after the reboot. However, the Assistant is listening and is responding. You can try asking it "What time it is". After it shows you the time it actually shows the Homescreen skill with a non-OVOS logo background. From looking at the logs everything seemed to load. Will be looking more at this.

As for the issue you posted, the issue is that OVOS sets file system permissions on /tmp/combo_locks to only itself. 
You can confirm with `ls -la /tmp/combo_locks`. Adding your own account to the `ovos` group does not work by itself b/c you also need to do chmod g+w on the folder periodically. The simpler route I found was to `sudo chsh ovos` by giving it a bash shell and then logging into it as `sudo su - ovos`, running as the limited ovos user from there.

**Comment by valorekhov** [comment]
@aka0kuro 
To resolve the issue with the homescreen skill not showing on boot up

you need to edit /etc/mycroft/mycroft.conf and remove setup from the following line:
```
"ready_settings": ["setup", "internet_skills"]
```

More info in this diff:
https://github.com/valorekhov/ovos-arch-linux/commit/dda9be3e23951003b7b605130d62ecd3d32edc63#diff-142ddc59afe2f657606a50a3cec2eea017bb6a196fdc85050b8eb66c66dccb52R2

**Comment by valorekhov** [comment]
Presuming this issue is closed
